### ISSUE TITLE
Seperate scraping / saving to DB

### ISSUE THREAD

**Issue by okin** [mdrenger/scrapeDA#8]
Currently we write any scraped entry to a database.
The scraper should only scrape. Saving the data should be another component.

**Comment by mdrenger** [comment]
consider those tables temporary, creating a stable dataset requires diff-ing several runs of the scraper

**Comment by okin** [comment]
Nonetheless i'd like to split everything up because dataset might not cover everyones use case.

And with a more split-up-setting we might also be able to easily integrate it into the scrapy processing pipeline.

**Comment by mdrenger** [comment]
yes, if you want to do that, feel free ;) maybe you could look at https://github.com/OpenRuhr/ris-scraper?files=1 before

**Comment by mweinelt** [comment]
Scrapy does not support python3 as per their documentation.

http://doc.scrapy.org/en/latest/faq.html#faq-python-versions
